//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercadoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mercadoria()
        {
            this.OrdemServicoItem = new HashSet<OrdemServicoItem>();
        }
    
        public int ID { get; set; }
        public bool EhServico { get; set; }
        public string Nome { get; set; }
        public decimal Preco { get; set; }
        public Nullable<int> Qtde { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoItem> OrdemServicoItem { get; set; }
    }
}
