//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServico()
        {
            this.OrdemServicoItem = new HashSet<OrdemServicoItem>();
        }
    
        public int ID { get; set; }
        public int ClienteID { get; set; }
        public System.DateTime DtAbertura { get; set; }
        public Nullable<System.DateTime> DtFechamento { get; set; }
        public string Observacao { get; set; }
        public string Situacao { get; set; }
        public string SituacaoDescricao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoItem> OrdemServicoItem { get; set; }
    }
}
